export const skillTags = [
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe After Effects",
  "UI Design",
  "UX Design",
  "Brand Identity",
  "Wireframing",
  "Prototyping",
  "TypeScript",
  "JavaScript",
  "React",
  "Next.js",
  "Node.js",
  "NestJS",
  "GraphQL",
  "REST APIs",
  "PostgreSQL",
  "Docker",
  "AWS",
  "CI/CD",
  "Testing",
  "SEO",
  "Paid Advertising",
  "Google Ads",
  "Meta Ads",
  "Email Marketing",
  "Content Strategy",
  "Copywriting",
  "Social Media Marketing",
  "Analytics",
  "SQL",
  "Python",
  "Tableau",
  "Power BI",
  "Machine Learning",
  "Data Visualization",
  "ETL",
  "A/B Testing",
  "Project Management",
  "Stakeholder Management",
  "Business Analysis",
  "Process Improvement",
  "Financial Modeling",
  "Budgeting",
  "Operations",
  "Strategy"
] as const;
